wallpaper {
    monitor = DP-2
    path = ~/Pictures/wallpapers/zvezda1.png
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-2
    path = ~/Pictures/wallpapers/zvezda1.png
    fit_mode = cover
}

wallpaper {
    monitor = eDP-1
    path = ~/Pictures/wallpapers/zvezda1.png
    fit_mode = cover
}

splash = false
